Agencia/Models/Destino.cs
using System.ComponentModel.DataAnnotations;

namespace Agencia.Models
{
    public class Destino
    {
        [Key]
        public int Id { get; set; }
        public string NomeDestino { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string Pais { get; set; }
    }
}

Agencia/Controllers/DestinoesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Agencia.Models;

namespace Agencia.Controllers
{
    public class DestinoesController : Controller
    {
        private readonly Context _context;

        public DestinoesController(Context context)
        {
            _context = context;
        }

        // GET: Destinoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Destino.ToListAsync());
        }

        // GET: Destinoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destino = await _context.Destino
                .FirstOrDefaultAsync(m => m.Id == id);
            if (destino == null)
            {
                return NotFound();
            }

            return View(destino);
        }

        // GET: Destinoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Destinoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomeDestino,Cidade,UF,Pais")] Destino destino)
        {
            if (ModelState.IsValid)
            {
                _context.Add(destino);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(destino);
        }

        // GET: Destinoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destino = await _context.Destino.FindAsync(id);
            if (destino == null)
            {
                return NotFound();
            }
            return View(destino);
        }

        // POST: Destinoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomeDestino,Cidade,UF,Pais")] Destino destino)
        {
            if (id != destino.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(destino);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DestinoExists(destino.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(destino);
        }

        // GET: Destinoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destino = await _context.Destino
                .FirstOrDefaultAsync(m => m.Id == id);
            if (destino == null)
            {
                return NotFound();
            }

            return View(destino);
        }

        // POST: Destinoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var destino = await _context.Destino.FindAsync(id);
            _context.Destino.Remove(destino);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DestinoExists(int id)
        {
            return _context.Destino.Any(e => e.Id == id);
        }
    }
}

Agencia/Controllers/HomeController.cs
using Agencia.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Agencia.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Destinos()
        {
            return View();
        }

        public IActionResult Promocoes()
        {
            return View();
        }

        public IActionResult Contato()
        {
            return View();
        }

        public IActionResult Destino()
        {
            return View();
        }

        public IActionResult Reserva()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Agencia/Controllers/ReservasController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Agencia.Models;

namespace Agencia.Controllers
{
    public class ReservasController : Controller
    {
        private readonly Context _context;

        public ReservasController(Context context)
        {
            _context = context;
        }

        // GET: Reservas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Reservas.ToListAsync());
        }

        // GET: Reservas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reservas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }

        // GET: Reservas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Reservas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomeDestino,DiasReserva,DataReserva")] Reserva reserva)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reserva);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reserva);
        }

        // GET: Reservas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reservas.FindAsync(id);
            if (reserva == null)
            {
                return NotFound();
            }
            return View(reserva);
        }

        // POST: Reservas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomeDestino,DiasReserva,DataReserva")] Reserva reserva)
        {
            if (id != reserva.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reserva);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservaExists(reserva.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reserva);
        }

        // GET: Reservas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reservas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }

        // POST: Reservas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reserva = await _context.Reservas.FindAsync(id);
            _context.Reservas.Remove(reserva);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservaExists(int id)
        {
            return _context.Reservas.Any(e => e.Id == id);
        }
    }
}

Agencia/Views/Home/Contato.cshtml
@{
    ViewData["Title"] = "Contato";
}

    <main>
        <section class="container">
            <div class="box">
                <form action="https://api.staticforms.xyz/submit" method="post">
                    <input type="hidden" name="accessKey" value="5c000c14-2996-46e0-a7d6-6fe1005dbfc1">
                    <fieldset>
                        <legend><b>Fale com a gente...</b></legend>
                        <br>
                        <div class="inputbox">
                            <input type="text" name="name" id="nome" class="inputUser" required>
                            <label for="nome" class="labelInput">Nome Completo</label>
                        </div>
                        <br><br>
                        <div class="inputbox">
                            <input type="text" name="email" id="email" class="inputUser" required>
                            <label for="email" class="labelInput">Email</label>
                        </div>
                        <br><br>
                        <div class="inputbox">
                            <input type="tel" name="telefone" id="telefone" class="inputUser" required>
                            <label for="telefone" class="labelInput">Telefone</label>
                        </div>
                        <br><br>
                        <div class="inputbox">
                            <label for="data_nascimento"><b>Data de nascimento</b></label>
                            <input type="date" name="data_nascimento" id="data_nascimento" required>
                        </div>
                        <br><br>
                        <div class="inputbox">
                            <textarea name="message" id="textarea" class="inputUser" rows="5" required></textarea>
                            <label for="textarea" class="labelInput">Escreva aqui...</label>
                        </div>
                        <br><br>
                        <input type="submit" name="submit" id="submit">
                    </fieldset>
                </form>
            </div>
        </section>
    </main>

Agencia/Views/Home/Destinos.cshtml
@{
    ViewData["Title"] = "Destinos";
}
    <main>
        <section class="container">
            <div class="botao">
                <a class="nav-link text-dark" asp-area="" asp-controller="Destinoes" asp-action="Index"><img src="~/img/destino.png" class="img-fluid"></a>
            </div>
            <div class="botao">
                <a class="nav-link text-dark" asp-area="" asp-controller="Reservas" asp-action="Index"><img src="~/img/reserva.png" class="img-fluid"></a>
            </div>
        </section>
        <br><br><br><br>
    </main>

Agencia/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
    <main>
        <!-- Propagandas/Carrousel -->
        <section class="container">
            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="~/img/banner1.jpg" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="~/img/banner2.png" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="~/img/banner3.png" class="d-block w-100" alt="...">
                  </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
        </section>

        <!-- Cartões -->
        <section class="container">
            <div class="item">
                <img src="~/img/cartoes.jpg">
            </div>
            <div class="item">
                <h1>Se sua vontade de viajar não é passageira,</h2>
                <h2>por que seus pontos tem que ser?</h3>
                <p>Com os Cartões Escape Viagens suas compras
                    valem pontos que não expiram para você trocar
                    pelo que quiser na Escape.
                </p>
            </div>
        </section>
    </main>

Agencia/Views/Home/Promocoes.cshtml
@{
    ViewData["Title"] = "Promocoes";
}
    <main>
        <section class="container">
            <div class="item">
                <a href="#"><img src="~/img/joaoPessoa.jpg"></a>
            </div>
            <div class="item">
                <h1>Pacotes para João Pessoa (OFERTA IMPERDÍVEL!)</h1>
                <p id="texto">Preço por pessoa</p>
                <h2 class="precoNovo">R$ 1.049</h2>
                <h4 class="precoAnt">R$ 1.409</h4>
                <p id="texto">Taxas e impostos não inclusos</p>
            </div>
        </section>
        <section class="container">
            <div class="item">
                <a href="#"><img src="~/img/fozIguacu.jpg"></a>
            </div>
            <div class="item">
                <h1>Pacotes para Foz do Iguaçu (OFERTA IMPERDÍVEL!)</h2>
                <p id="texto">Preço por pessoa</p>
                <h2 class="precoNovo">R$ 873</h2>
                <h4 class="precoAnt">R$ 1.205</h4>
                <p id="texto">Taxas e impostos não inclusos</p>
            </div>
        </section>        <section class="container">
            <div class="item">
                <a href="#"><img src="~/img/curitiba.jpg"></a>
            </div>
            <div class="item">
                <h1>Pacotes para Curitiba (OFERTA IMPERDÍVEL!)</h2>
                <p id="texto">Preço por pessoa</p>
                <h2 class="precoNovo">R$ 672</h2>
                <h4 class="precoAnt">R$ 809</h4>
                <p id="texto">Taxas e impostos não inclusos</p>
        </section>
    </main>